// This file was generated by Slater.app - odometers.js


gsap.registerPlugin(ScrollTrigger);

function initNumberOdometer() {
  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches
  const initFlag = 'data-odometer-initialized'
  const activeTweens = new WeakMap()

  // EDIT (persistent mode): elements whose roller DOM stays alive
  // between updates — see updatePersistent() below
  const persistentStates = new Map()
  const persistentEls = new Set()

  // EDIT (proportional digits): per-element cache of digit widths,
  // bleed padding, and ink metrics for optical alignment
  const digitWidthCache = new WeakMap()

  // Configuration
  const defaults = {
    duration: 1,
    ease: 'power3.out',
    elementStagger: 0.1,
    digitStagger: 0.04,
    revealDuration: 0.5,
    revealEase: 'power2.out',
    triggerStart: 'top 80%',
    staggerOrder: 'left',
    digitCycles: 2
  }

  // EDIT (proportional digits): the column width for a digit =
  // natural glyph width (incl. letter-spacing) + bleed padding
  function colWidth(widths, d) {
    return widths.digits[d] + widths.pad
  }

  // Scroll-triggered groups
  document.querySelectorAll('[data-odometer-group]').forEach(group => {
    if (group.hasAttribute(initFlag)) return
    group.setAttribute(initFlag, '')

    const elements = Array.from(group.querySelectorAll('[data-odometer-element]'))
    if (!elements.length || prefersReducedMotion) return

    const staggerOrder = group.getAttribute('data-odometer-stagger-order') || defaults
      .staggerOrder
    const triggerStart = group.getAttribute('data-odometer-trigger-start') || defaults
      .triggerStart
    const elementStagger = parseFloat(group.getAttribute('data-odometer-stagger')) || defaults
      .elementStagger

    const elementData = elements.map(el => {
      const originalText = el.textContent.trim()
      const hasExplicitStart = el.hasAttribute('data-odometer-start')
      const startValue = parseFloat(el.getAttribute('data-odometer-start')) || 0
      const duration = parseFloat(el.getAttribute('data-odometer-duration')) || defaults
        .duration
      const step = getLineHeightRatio(el)

      let segments = parseSegments(originalText)
      segments = mapStartDigits(segments, startValue)
      segments = markHiddenSegments(segments, startValue)

      const grow = shouldGrow(el, hasExplicitStart, startValue, segments)
      const { rollers, revealEls, widths } = buildRollerDOM(el, segments, step, grow)

      const fontSize = parseFloat(getComputedStyle(el).fontSize)
      const revealData = revealEls.map(revealEl => {
        const widthEm = revealEl.offsetWidth / fontSize
        gsap.set(revealEl, { width: 0, overflow: 'hidden' })
        return { el: revealEl, widthEm }
      })

      return { el, rollers, duration, step, revealData, originalText, widths }
    })

    const ordered = applyStaggerOrder(elementData, staggerOrder)

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: group,
        start: triggerStart,
        once: true
      },
      onComplete() {
        elementData.forEach(({ el, originalText, step }) => {
          cleanupElement(el, originalText)
        })
      }
    })

    ordered.forEach((data, orderIdx) => {
      const { rollers, duration, step, revealData, widths } = data
      const offset = orderIdx * elementStagger

      revealData.forEach(({ el, widthEm }) => {
        tl.to(el, {
          width: widthEm + 'em',
          opacity: 1,
          duration: defaults.revealDuration,
          ease: defaults.revealEase
        }, offset)
      })

      rollers.forEach(({ roller, targetPos, mask, endDigit }, digitIdx) => {
        const reversedIdx = rollers.length - 1 - digitIdx
        tl.to(roller, {
          y: -targetPos * step + 'em',
          duration,
          ease: defaults.ease,
          force3D: true
        }, offset + reversedIdx * defaults.digitStagger)

        // EDIT (proportional digits): the column morphs to the
        // landed digit's natural width while the roll runs
        if (mask && typeof endDigit === 'number') {
          tl.to(mask, {
            width: colWidth(widths, endDigit) + 'em',
            duration,
            ease: defaults.ease
          }, offset + reversedIdx * defaults.digitStagger)
        }
      })
    })
  })

  // ==================================================================
  // EDIT (persistent mode): for values that update repeatedly (the
  // countdown), the roller DOM is built ONCE and every update just
  // retargets the same rollers. Positions are tracked as LOGICAL
  // numbers (r.pos, in cells) — pixels are write-only, so a
  // one-step change is always exactly one cell and interrupted
  // rolls continue fluidly from their fractional position.
  // ==================================================================
  function updatePersistent(el, newText, options) {
    const duration = options.duration ?? defaults.duration
    const ease = options.ease || defaults.ease
    const step = getLineHeightRatio(el)

    const newDigits = [...newText].filter(c => /\d/.test(c)).map(Number)

    let state = persistentStates.get(el)
    const valid = state &&
      state.rollers.length === newDigits.length &&
      state.rollers.every(r => r.roller.isConnected)

    if (!valid) {
      // (Re)build once, seating each roller on the digit currently
      // shown so the first roll starts from the right place
      if (state && state.tl) state.tl.kill()
      const currentText = el.textContent.trim()
      const startValue = parseInt(
        [...currentText].filter(c => /\d/.test(c)).join(''), 10
      ) || 0

      let segments = parseSegments(newText)
      segments = mapStartDigits(segments, startValue)
      const { rollers, widths } = buildRollerDOM(el, segments, step, false)

      const digitSegs = segments.filter(s => s.type === 'digit')
      state = {
        // pos = logical position in cells — the single source of
        // truth for where this roller is, never read from pixels
        rollers: rollers.map((r, i) => ({
          roller: r.roller,
          mask: r.mask, // EDIT (proportional digits)
          pos: digitSegs[i].startDigit || 0,
        })),
        widths, // EDIT (proportional digits)
        tl: null,
      }
      persistentStates.set(el, state)
      persistentEls.add(el)
    }

    // Retarget — killing an in-flight roll leaves r.pos at its exact
    // fractional value, so the new roll continues from mid-air
    if (state.tl) {
      state.tl.kill()
      state.tl = null
    }

    const goingDown = options.direction === 'down'

    const tl = gsap.timeline({
      onComplete() {
        if (state.tl === tl) state.tl = null
      }
    })
    state.tl = tl

    state.rollers.forEach((r, i) => {
      const endDigit = newDigits[i]

      // Normalise into one cycle [0,10) — shifting by whole cycles
      // is pixel-identical because the cells repeat every 10
      r.pos = r.pos - Math.floor(r.pos / 10) * 10
      const normPos = r.pos

      // Already resting on the target digit → just re-seat exactly
      if (Math.abs(normPos - endDigit) < 0.001) {
        r.pos = endDigit
        gsap.set(r.roller, { y: -endDigit * step + 'em', force3D: true })
        // EDIT (proportional digits): make sure the column matches
        gsap.set(r.mask, { width: colWidth(state.widths, endDigit) + 'em' })
        return
      }

      let target
      if (goingDown) {
        // Seat one cycle up (visually identical) so there is always
        // room to roll backwards, then take the short way down
        r.pos = normPos + 10
        target = endDigit < normPos ? endDigit + 10 : endDigit
      } else {
        target = endDigit > normPos ? endDigit : endDigit + 10
      }

      gsap.set(r.roller, { y: -r.pos * step + 'em', force3D: true })

      const reversedIdx = state.rollers.length - 1 - i
      tl.to(r, {
        pos: target,
        duration,
        ease,
        onUpdate() {
          gsap.set(r.roller, { y: -r.pos * step + 'em', force3D: true })
        },
      }, reversedIdx * defaults.digitStagger)

      // EDIT (proportional digits): the column width follows the
      // roll — every tick the digits re-space like typeset text
      tl.to(r.mask, {
        width: colWidth(state.widths, endDigit) + 'em',
        duration,
        ease,
      }, reversedIdx * defaults.digitStagger)
    })
  }

  // Programmatic update (optional add-on)
  return function updateOdometer(el, newText, options = {}) {
    // EDIT (persistent mode): repeatedly-updating values keep their
    // roller DOM alive — no cleanup swap, no rebuild per change
    if (options.persistent) {
      updatePersistent(el, newText, options)
      return
    }

    // EDIT (about count integration): force-complete any running roll
    // BEFORE reading the current text — progress(1) fires onComplete
    // → cleanupElement, so el.textContent is a clean number again
    // when we parse it as the start value.
    const existing = activeTweens.get(el)
    if (existing) {
      existing.progress(1)
      existing.kill()
      activeTweens.delete(el)
      gsap.set(el, { clearProps: 'width,overflow' })
    }

    const currentText = el.textContent.trim()
    if (currentText === newText) return

    const duration = options.duration || defaults.duration
    const ease = options.ease || defaults.ease
    const step = getLineHeightRatio(el)

    // Measure current width before rebuilding (in em for responsive scaling)
    const fontSize = parseFloat(getComputedStyle(el).fontSize)
    const oldWidthEm = el.getBoundingClientRect().width / fontSize

    // Parse current text as start, new text as end
    const startSegments = parseSegments(currentText)
    const startDigitsStr = startSegments
      .filter(s => s.type === 'digit')
      .map(s => s.char)
      .join('')
    const startValue = parseInt(startDigitsStr, 10) || 0

    let segments = parseSegments(newText)
    segments = mapStartDigits(segments, startValue)
    segments = markHiddenSegments(segments, startValue)
    // EDIT (loader integration): read the grow option instead of
    // hardcoding true — default behavior stays unchanged
    const grow = options.grow !== false
    const { rollers, revealEls, widths } = buildRollerDOM(el, segments, step, grow)

    // EDIT (loader integration): optional "from blank" start — every
    // digit roller begins on an empty cell and rolls one full cycle
    // in to its target value
    if (options.fromBlank) {
      rollers.forEach(r => {
        gsap.set(r.roller, { y: step + 'em' })
        r.targetPos = 10 + (r.targetPos % 10)
      })
    }
    // EDIT (about count integration): optional backwards roll.
    else if (options.direction === 'down') {
      const digitSegs = segments.filter(s => s.type === 'digit')
      rollers.forEach((r, i) => {
        const startDigit = digitSegs[i].startDigit || 0
        const endDigit = parseInt(digitSegs[i].char, 10)
        gsap.set(r.roller, { y: -(10 + startDigit) * step + 'em' })
        r.targetPos = endDigit <= startDigit ? 10 + endDigit : endDigit
      })
    }

    // Measure new natural width (in em) — masks are seated at their
    // START digit widths, the per-mask tweens below carry the
    // element to its true end width naturally
    const newWidthEm = el.getBoundingClientRect().width / fontSize
    const widthChanged = Math.abs(oldWidthEm - newWidthEm) > 0.01

    // Lock to old width for smooth transition
    if (widthChanged) {
      gsap.set(el, { width: oldWidthEm + 'em', overflow: 'hidden' })
    }

    const tl = gsap.timeline({
      onComplete() {
        cleanupElement(el, newText)
        activeTweens.delete(el)
      }
    })
    activeTweens.set(el, tl)

    // Animate element width
    if (widthChanged) {
      tl.to(el, {
        width: newWidthEm + 'em',
        duration: defaults.revealDuration,
        ease: defaults.revealEase
      }, 0)
    }

    // Fade in hidden statics
    revealEls.forEach(revealEl => {
      if (revealEl.getAttribute('data-odometer-part') === 'static') {
        tl.to(revealEl, { opacity: 1, duration: 0.2 }, 0)
      }
    })

    // Roll digits
    rollers.forEach(({ roller, targetPos, mask, endDigit }, digitIdx) => {
      const reversedIdx = rollers.length - 1 - digitIdx
      tl.to(roller, {
        y: -targetPos * step + 'em',
        duration,
        ease,
        force3D: true
      }, reversedIdx * defaults.digitStagger)

      // EDIT (proportional digits): column morphs to the landed
      // digit's natural width during the roll
      if (mask && typeof endDigit === 'number') {
        tl.to(mask, {
          width: colWidth(widths, endDigit) + 'em',
          duration,
          ease
        }, reversedIdx * defaults.digitStagger)
      }
    })
  }

  // Helpers
  function getLineHeightRatio(el) {
    const cs = getComputedStyle(el)
    const lh = cs.lineHeight
    if (lh === 'normal') return 1.2
    return parseFloat(lh) / parseFloat(cs.fontSize)
  }

  // EDIT (proportional digits + letter-spacing + optical statics):
  // per-element measurement of:
  //  - digits: natural width of 0–9 (em), measured with
  //    letter-spacing 0, then the inherited letter-spacing added,
  //    so each column = advance + letter-spacing (normal text
  //    footprint)
  //  - pad: the mask's horizontal bleed padding (em) — under
  //    border-box an explicit width includes it, so it's added on
  //    top of every column width
  //  - ink: canvas TextMetrics ink boxes for optical alignment of
  //    statics. Lining digits span baseline→cap-height, but
  //    punctuation like ':' is designed to sit low. Statics are
  //    nudged so their ink center matches the DIGITS' ink center.
  //    Digits themselves stay on the true baseline, so the
  //    text-trim system keeps lining up with surrounding text.
  function getDigitWidths(el) {
    const cached = digitWidthCache.get(el)
    if (cached) return cached
    const cs = getComputedStyle(el)
    const fontSize = parseFloat(cs.fontSize)
    const ls = cs.letterSpacing === 'normal' ?
      0 :
      (parseFloat(cs.letterSpacing) || 0) / fontSize

    const probe = document.createElement('span')
    probe.style.position = 'absolute'
    probe.style.visibility = 'hidden'
    probe.style.whiteSpace = 'pre'
    probe.style.lineHeight = '1'
    probe.style.letterSpacing = '0' // deterministic glyph advance
    el.appendChild(probe)
    const digits = {}
    for (let d = 0; d <= 9; d++) {
      probe.textContent = String(d)
      digits[d] = probe.getBoundingClientRect().width / fontSize + ls
    }
    probe.remove()

    const maskProbe = document.createElement('span')
    maskProbe.setAttribute('data-odometer-part', 'mask')
    maskProbe.style.position = 'absolute'
    maskProbe.style.visibility = 'hidden'
    el.appendChild(maskProbe)
    const mcs = getComputedStyle(maskProbe)
    const pad = mcs.boxSizing === 'border-box' ?
      (parseFloat(mcs.paddingLeft) + parseFloat(mcs.paddingRight)) / fontSize :
      0
    maskProbe.remove()

    // Ink metrics via canvas — the ink center of a glyph is
    // (ascent − descent) / 2 above the baseline (em)
    const ink = { supported: false, digitCenter: 0, chars: {} }
    try {
      const ctx = document.createElement('canvas').getContext('2d')
      ctx.font =
        cs.fontStyle + ' ' + cs.fontWeight + ' ' + fontSize + 'px ' + cs.fontFamily
      const m = ctx.measureText('0')
      if (typeof m.actualBoundingBoxAscent === 'number') {
        ink.supported = true
        ink.digitCenter =
          (m.actualBoundingBoxAscent - m.actualBoundingBoxDescent) / 2 / fontSize
        ink.measure = function (ch) {
          if (ink.chars[ch] === undefined) {
            const cm = ctx.measureText(ch)
            ink.chars[ch] =
              (cm.actualBoundingBoxAscent - cm.actualBoundingBoxDescent) / 2 / fontSize
          }
          return ink.chars[ch]
        }
      }
    } catch (e) { /* canvas unavailable → no optical nudge */ }

    const cache = { digits, pad, ink }
    digitWidthCache.set(el, cache)
    return cache
  }

  function parseSegments(text) {
    return [...text].map(char => ({
      type: /\d/.test(char) ? 'digit' : 'static',
      char
    }))
  }

  function mapStartDigits(segments, startValue) {
    const digitSlots = segments.filter(s => s.type === 'digit')
    const padded = String(Math.floor(Math.abs(startValue)))
      .padStart(digitSlots.length, '0')
      .slice(-digitSlots.length)
    let di = 0
    return segments.map(s =>
      s.type === 'digit' ? { ...s, startDigit: parseInt(padded[di++], 10) } :
      s
    )
  }

  function markHiddenSegments(segments, startValue) {
    const totalDigits = segments.filter(s => s.type === 'digit').length
    const absStart = Math.floor(Math.abs(startValue))
    const startDigitCount = absStart === 0 ? 1 : String(absStart).length
    const leadingZeros = Math.max(0, totalDigits - startDigitCount)
    if (leadingZeros === 0) return segments
    let digitsSeen = 0
    let firstDigitSeen = false
    let prevDigitHidden = false
    return segments.map(seg => {
      if (seg.type === 'digit') {
        firstDigitSeen = true
        const hidden = digitsSeen < leadingZeros
        prevDigitHidden = hidden
        digitsSeen++
        return { ...seg, hidden }
      }
      const hidden = firstDigitSeen && prevDigitHidden
      return { ...seg, hidden }
    })
  }

  function shouldGrow(el, hasExplicitStart, startValue, segments) {
    if (el.hasAttribute('data-odometer-grow')) {
      return el.getAttribute('data-odometer-grow') !== 'false'
    }
    if (!hasExplicitStart) return false
    const absStart = Math.floor(Math.abs(startValue))
    const startDigitCount = absStart === 0 ? 1 : String(absStart).length
    const endDigitCount = segments.filter(s => s.type === 'digit').length
    return startDigitCount < endDigitCount
  }

  function buildRollerDOM(el, segments, step, grow) {
    // EDIT (proportional digits): measure BEFORE clearing so the
    // probes inherit a clean context either way
    const widths = getDigitWidths(el)

    el.innerHTML = ''
    el.style.height = ''
    const rollers = []
    const revealEls = []
    const totalCells = 10 * defaults.digitCycles
    segments.forEach(seg => {
      if (seg.type === 'static') {
        const span = document.createElement('span')
        span.setAttribute('data-odometer-part', 'static')
        span.style.height = step + 'em'
        span.style.lineHeight = step
        span.textContent = seg.char

        // EDIT (optical statics): nudge the static so its ink
        // center matches the digits' ink center — e.g. ':' is
        // designed to sit low next to lowercase, and reads as
        // sagging next to tall lining digits. delta > 0 means the
        // static's ink sits LOWER than the digits' → move it up.
        if (widths.ink.supported && seg.char.trim()) {
          const delta = widths.ink.digitCenter - widths.ink.measure(seg.char)
          if (Math.abs(delta) > 0.002) {
            span.style.transform = 'translateY(' + (-delta).toFixed(4) + 'em)'
          }
        }

        el.appendChild(span)
        if (grow && seg.hidden) {
          gsap.set(span, { opacity: 0 })
          revealEls.push(span)
        }
        return
      }
      const mask = document.createElement('span')
      mask.setAttribute('data-odometer-part', 'mask')
      mask.style.height = step + 'em'
      mask.style.lineHeight = step
      const roller = document.createElement('span')
      roller.setAttribute('data-odometer-part', 'roller')
      roller.style.lineHeight = step

      // EDIT (Safari fix): each digit gets its own block-level cell
      // with an explicit height in em — WebKit rounds text line
      // boxes to whole pixels, explicit heights lay out with
      // subpixel precision, so cell N sits at exactly N * step em.
      for (let d = 0; d < totalCells; d++) {
        const cell = document.createElement('span')
        cell.setAttribute('data-odometer-part', 'cell')
        cell.style.display = 'block'
        cell.style.height = step + 'em'
        cell.style.lineHeight = step
        cell.textContent = String(d % 10)
        roller.appendChild(cell)
      }
      mask.appendChild(roller)
      el.appendChild(mask)
      const startDigit = seg.startDigit || 0
      const endDigit = parseInt(seg.char, 10)
      const isReveal = grow && seg.hidden

      // EDIT (proportional digits): the mask is pinned to the
      // natural width of the digit it currently shows (+ bleed
      // padding compensation). Reveal columns seat at their END
      // width. Wider digits passing through during a roll clip
      // symmetrically at the column edges — reads as motion, and
      // the resting state is always exact natural spacing.
      mask.style.width = colWidth(widths, isReveal ? endDigit : startDigit) + 'em'

      gsap.set(roller, { y: isReveal ? step + 'em' : -startDigit * step + 'em' })
      const targetPos = endDigit > startDigit ? endDigit : 10 + endDigit
      rollers.push({ roller, targetPos, mask, endDigit, startDigit })
      if (isReveal) revealEls.push(mask)
    })
    return { rollers, revealEls, widths }
  }

  function cleanupElement(el, originalText) {
    el.style.overflow = ''
    el.style.height = ''

    // Remove rollers, set final digit, clear inline bloat (but preserve width)
    const digits = [...originalText].filter(c => /\d/.test(c))
    let di = 0

    el.querySelectorAll('[data-odometer-part="mask"]').forEach(mask => {
      // EDIT (landing snap fix + proportional digits): pin the mask
      // to its roll-time width before swapping in the plain digit.
      // rect width includes the bleed padding under border-box, so
      // the pinned value stays consistent with the widths we set.
      const fontSize = parseFloat(getComputedStyle(mask).fontSize)
      const widthEm = mask.getBoundingClientRect().width / fontSize
      mask.style.width = widthEm + 'em'

      const roller = mask.querySelector('[data-odometer-part="roller"]')
      if (roller) roller.remove()
      mask.textContent = digits[di++] || ''
      mask.style.opacity = ''
      mask.style.overflow = ''
    })

    // EDIT (optical statics): the transform nudge is inline on the
    // static span and statics survive cleanup untouched apart from
    // opacity — so the optical alignment persists at rest
    el.querySelectorAll('[data-odometer-part="static"]').forEach(stat => {
      stat.style.opacity = ''
    })
  }

  function recalcOnResize() {
    document.querySelectorAll('[data-odometer-element]').forEach(el => {
      // Force-complete any running programmatic animation
      const running = activeTweens.get(el)
      if (running) {
        running.progress(1)
        activeTweens.delete(el)
      }

      const hasRollers = el.querySelector('[data-odometer-part="roller"]')

      if (hasRollers) {
        // Pre-triggered: recalculate step-based inline styles
        // (mask widths + static nudges are em-based → scale
        // automatically)
        const step = getLineHeightRatio(el)
        el.querySelectorAll('[data-odometer-part="mask"]').forEach(mask => {
          mask.style.height = step + 'em'
          mask.style.lineHeight = step
        })
        el.querySelectorAll('[data-odometer-part="roller"]').forEach(roller => {
          roller.style.lineHeight = step
        })
        el.querySelectorAll('[data-odometer-part="cell"]').forEach(cell => {
          cell.style.height = step + 'em'
          cell.style.lineHeight = step
        })
        el.querySelectorAll('[data-odometer-part="static"]').forEach(stat => {
          stat.style.lineHeight = step
        })
      }
      // Completed elements: width is em-based, scales automatically, don't touch
    })

    // EDIT (persistent mode): force in-flight rolls to their end,
    // refresh step-based styles, re-seat rollers from their logical
    // positions, and re-pin mask widths from the em cache
    persistentEls.forEach(el => {
      const state = persistentStates.get(el)
      if (!state) return
      if (state.tl) {
        state.tl.progress(1)
        state.tl.kill()
        state.tl = null
      }
      const step = getLineHeightRatio(el)
      el.querySelectorAll('[data-odometer-part="mask"]').forEach(mask => {
        mask.style.height = step + 'em'
        mask.style.lineHeight = step
      })
      el.querySelectorAll('[data-odometer-part="roller"]').forEach(roller => {
        roller.style.lineHeight = step
      })
      el.querySelectorAll('[data-odometer-part="cell"]').forEach(cell => {
        cell.style.height = step + 'em'
        cell.style.lineHeight = step
      })
      el.querySelectorAll('[data-odometer-part="static"]').forEach(stat => {
        stat.style.lineHeight = step
      })
      state.rollers.forEach(r => {
        r.pos = r.pos - Math.floor(r.pos / 10) * 10
        gsap.set(r.roller, { y: -r.pos * step + 'em', force3D: true })
        // EDIT (proportional digits): re-seat the column width too
        const digit = Math.round(r.pos) % 10
        gsap.set(r.mask, { width: colWidth(state.widths, digit) + 'em' })
      })
    })

    ScrollTrigger.refresh()
  }

  let resizeTimer
  let lastWidth = window.innerWidth
  window.addEventListener('resize', () => {
    clearTimeout(resizeTimer)
    resizeTimer = setTimeout(() => {
      if (window.innerWidth === lastWidth) return
      lastWidth = window.innerWidth
      recalcOnResize()
    }, 250)
  })

  function applyStaggerOrder(items, order) {
    const arr = [...items]
    if (order === 'right') return arr.reverse()
    if (order === 'random') return shuffleArray(arr)
    return arr
  }

  function shuffleArray(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]]
    }
    return arr
  }
}

// EDIT (loader integration): store the updater so the loader
// can drive programmatic counts
window.updateOdometer = initNumberOdometer();


