// This file was generated by Slater.app - Nick Ho

let paths = window.location.pathname.split('/')


// bg-text-animations -> 
import('https://slater.app/20545/62861.js?v=703131')


// buttons -> 
import('https://slater.app/20545/62796.js?v=369365')


// cursor-follow-tag -> 
import('https://slater.app/20545/62860.js?v=375256')


// global-parallax -> 
import('https://slater.app/20545/62847.js?v=504992')


// global-scroll-into-view-animations -> 
import('https://slater.app/20545/63183.js?v=387703')


// line-on-scroll -> 
import('https://slater.app/20545/62848.js?v=11498')


// load-animation -> DISABLED (replaced by custom loader-animation.js)
// import('https://slater.app/20545/62715.js?v=32696')


// menu -> 
import('https://slater.app/20545/62816.js?v=866265')


// odometers -> 
import('https://slater.app/20545/62716.js?v=509246')


// section-overlap -> 
import('https://slater.app/20545/63239.js?v=121696')


// sound-cursor-label-switch -> 
import('https://slater.app/20545/63919.js?v=559023')


// svg-flicker -> 
import('https://slater.app/20545/62442.js?v=501693')


// videos-bunny -> 
import('https://slater.app/20545/63247.js?v=786345')


// (NA) hero-trail-v1 -> 

// (NA) hero-trail-v1 has not been connected to a Webflow page.

// (NA) history-image-ratio  -> 

// (NA) history-image-ratio  has not been connected to a Webflow page.

// (NA) history-sticky-section + mobile -> 

// (NA) history-sticky-section + mobile has not been connected to a Webflow page.

// (NA) saturation-hover -> 

// (NA) saturation-hover has not been connected to a Webflow page.

// agenda-scroll -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/62406.js?v=427322'); 
} 
 

// countdown-next-race -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/63307.js?v=464018'); 
} 
 

// helmet-cursor -> DISABLED (helmet replaced with laptop, see js/laptop-loader.js)
// Original: import('https://slater.app/20545/63181.js?v=77039')
 

// helmet-scroll -> DISABLED (helmet replaced with laptop, see js/laptop-loader.js)
// Original: import('https://slater.app/20545/63174.js?v=719962')
 

// laptop-loader -> custom GLB laptop replacing helmet
import('./laptop-loader.js');
 

// hero-3d-setup -> local copy with tuned fluid config
import('./hero-3d-setup.js'); 
 

// history-sticky-section -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/63069.js?v=464201'); 
} 
 

// logo-marquee -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/62670.js?v=286324'); 
} 
 

// media-slider -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/62643.js?v=122369'); 
} 
 

// mobile-hero-98-scrolltrigger -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/63560.js?v=60699'); 
} 
 

// quote-images-scroll -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/62857.js?v=68706'); 
} 
 

// radial-slider -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/62450.js?v=767932'); 
} 
 

// video-mask-animation -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/20545/63252.js?v=467902'); 
} 
 

